name: flutter_appauth_web
description: Web OAuth wrapper
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: '>=0.13.3 <1.0.0'
  flutter_appauth_platform_interface: '>=3.0.0 <4.0.0'
  platform_detect: '>=2.0.0 <3.0.0'
  pointycastle: '>=3.3.4  <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_appauth: '>=1.0.0 <2.0.0'

flutter:
  plugin:
    platforms:
      web:
        pluginClass: AppAuthWebPlugin
        fileName: flutter_appauth_web.dart
